trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  bucket: pragma-tf-pipeline-artifacts
# - group: FullStack
#   AWS_ACCESS_KEY_ID: <tu-access-key-id>
#   AWS_SECRET_ACCESS_KEY: <tu-secret-access-key>
#   AWS_DEFAULT_REGION: <tu-region-de-aws>
#   AWS_S3_BUCKET: <nombre-del-bucket-en-s3>
#   APPLICATION_NAME: <nombre-de-la-aplicacion-en-beanstalk>
#   ENVIRONMENT_NAME: <nombre-del-entorno-en-beanstalk>

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run lint
    npm install --global prettier
    npm run prettier --check
    CI=true npm run test
    npm run build
  displayName: 'Build and Test'

- bash: |
    mkdir ~/.aws
    cat >> ~/.aws/credentials << EOL
    [default]
    aws_access_key_id=$(AWS_ACCESS)
    aws_secret_access_key=$(AWS_SECRET)
    EOL
  displayName: 'Set AWS credentials'

- bash: | 
    echo $AWS_ACCESS
    echo $AWS_SECRET
  displayName: 'Variables'


- task: AWSCLI@1
  inputs:
    awsCredentials: 'AWS'
    regionName: 'us-west-2'
    command: 'aws s3 cp'
    arguments: './build.zip s3://$(bucket)/build.zip'
  displayName: 'Upload Artifact to S3'
  # env:
  #   AWS_ACCESS_KEY_ID: $(AWS_ACCESS)
  #   AWS_SECRET_ACCESS_KEY: $(AWS_SECRET)

- task: AWSCLI@1
  inputs:
    awsCredentials: 'AWS'
    regionName: 'us-west-2'
    awsCommand: 'elasticbeanstalk create-application-version'
    arguments: '--application-name myapp --version-label $(Build.BuildId) --source-bundle S3Bucket=$(bucket),S3Key=build.zip'
  displayName: 'Create Beanstalk Application Version'

- task: AWSCLI@1
  inputs:
    awsCredentials: 'AWS'
    regionName: 'us-west-2'
    awsCommand: 'elasticbeanstalk update-environment'
    arguments: '--environment-name myenv --version-label $(Build.BuildId)'
  displayName: 'Deploy to Beanstalk'  