trigger:
- master

pool:
  vmImage: ubuntu-latest

# variables:
#   AWS_ACCESS_KEY_ID: <tu-access-key-id>
#   AWS_SECRET_ACCESS_KEY: <tu-secret-access-key>
#   AWS_DEFAULT_REGION: <tu-region-de-aws>
#   AWS_S3_BUCKET: <nombre-del-bucket-en-s3>
#   APPLICATION_NAME: <nombre-de-la-aplicacion-en-beanstalk>
#   ENVIRONMENT_NAME: <nombre-del-entorno-en-beanstalk>

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run lint
    npm install --global prettier
    npm run prettier --check
    CI=true npm run test
    npm run build
  displayName: 'Build and Test'

- task: AWSCLI@1
  inputs:
    awsCredentials: 'AWS'
    regionName: 'us-west-2'
    command: 's3 cp'
    arguments: './build.zip s3://pragma-tf-pipeline-artifacts/build.zip'
  displayName: 'Upload Artifact to S3'