trigger:
- master

pool:
  vmImage: ubuntu-latest

# variables:
#   AWS_ACCESS_KEY_ID: <tu-access-key-id>
#   AWS_SECRET_ACCESS_KEY: <tu-secret-access-key>
#   AWS_DEFAULT_REGION: <tu-region-de-aws>
#   AWS_S3_BUCKET: <nombre-del-bucket-en-s3>
#   APPLICATION_NAME: <nombre-de-la-aplicacion-en-beanstalk>
#   ENVIRONMENT_NAME: <nombre-del-entorno-en-beanstalk>

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm test
    npm run build
    npm install -g aws-sdk
    aws s3 cp build s3://pragma-tf-pipeline-artifacts/build --recursive
  displayName: 'npm install, test, build, and upload to S3'